### ISSUE TITLE
Animation overlap

### ISSUE THREAD

**Issue by h77ps** [angelsix/fasetto-word#10]
It is possible for the user to trigger any of the slide in animations multiple times if they are quicker with the click than the 0.3f animation duration. This causes the container to finish animating the margin but the visibility doesn't get set up properly. 

To test:  Click to open the "Attach a file..." dialog and double click on the paper clip. It will cause the popup to hide and show but once the show animation is complete it becomes invisible.

**Comment by angelsix** [comment]
Fixed https://github.com/angelsix/fasetto-word/commit/4dc109ed26b671b7d83148c470bc636227243d1b

It was not an animation overlap as such, it was just the logic we set the visibility to hidden after the animations original timeout
