### ISSUE TITLE
Memory Leak in FrameworkElementAnimationAttachedProperties

### ISSUE THREAD

**Issue by TomTomB** [angelsix/fasetto-word#12]
Hi there,

I think I´ve foud a memory leak in the "Animation stuff". 

How did I achive this: 
I created my own application with your YouTube series. It relies heavily on navigation through pages. 
So, as soon as the user navigates to an other page, the old page should be destructed by the GC, but it´s not. It simply stays in the RAM. 
I guess that´s due to some references in the  FrameworkElementAnimationAttachedProperties.cs . 
I think it´s propably the method that defines if the firstload flag is true or false.

I´ve also created a small application using PRISM to test if there is just a bug in my code, but that ended up with the same memory leak.

Cheers

**Comment by angelsix** [comment]
Yes right now anywhere we do += to an event will contain memory leaks. I will clean this up with Weak Events soon or you can read up here https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/weak-event-patterns

**Comment by TomTomB** [comment]
Mhm I think that´s an other story. I´ve just figured out what the reason for my mentioned memory leak is. 
But I don´t know how to properly fix that. 

Inside `AnimateBaseProperty<Parent>` you´ve created 2 dictionaries storing all the Framwork Elements that got animation properties. Changing the types e.g. `Dictionary<DependencyObject, bool> mAlreadyLoaded` to `Dictionary<string, bool> mAlreadyLoaded` fixes my memory leak since from now on only the names of the Framework Elements are stored. 

Again, I won´t use that as a solution - just thought it´s maybe some useful information.

**Comment by angelsix** [comment]
Can you verify it is fixed here then I will close
https://github.com/angelsix/fasetto-word/commit/d24cbc35052b3c199f14d820ba14b274933b75d5

**Comment by TomTomB** [comment]
Hi,
yes it´s working perfectly fine now.
So I´ll guess this one can be closed.
