### ISSUE TITLE
Cannot bind different loggers in App.xaml.cs

### ISSUE THREAD

**Issue by lorentzfb** [angelsix/fasetto-word#13]
First of all, great video series and tutorial!

How can we bind different loggers? It seems that only the same type of loggers can be bound using the code below.

**App.xaml.cs**

```
            // Bind file logger(s)
            IoC.Kernel.Bind<ILogFactory>().ToConstant(new BaseLogFactory(new[]
            {
                // TODO: Add ApplicationSettings so we can set/edit a log location
                //       For now just log to the path where this application is running
                new FileLogger("log.txt"),
                new ConsoleLogger()
            }));
```

**Error:**
`CS0826 No best type found for implicitly-typed array`

**Comment by lorentzfb** [comment]
I think this solved it:

Added `Ilogger `as array type.

```
IoC.Kernel.Bind<ILogFactory>().ToConstant(new BaseLogFactory(new ILogger[]
            {
```

**Comment by angelsix** [comment]
You shouldn't have a problem if each logger implements ILogger. Can you provide a code example
