### ISSUE TITLE
Error loading project

### ISSUE THREAD

**Issue by vikasjha1995** [angelsix/fasetto-word#14]
Hi I have vs2015 community and now while building the latest solution I m getting the following error
please provide some solution or name the commits up to which I can run it.

Severity	Code	Description	Project	File	Line	Suppression State
Error		The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.	Fasetto.Word	D:\vj\wpf\chat application\fasetto-word-develop\Source\Fasetto.Word.Core\Fasetto.Word.Core.csproj	1

**Comment by angelsix** [comment]
The project isn't officially supporting VS 2015 there is no need, just update to VS 2017. However I suspect your issue is due to using .Net Framework 4.7.1... not sure if VS 2015 supports that? You can try installing the 4.7.1 SDK  https://www.microsoft.com/net/download/visual-studio-sdks
