### ISSUE TITLE
somes errors on first build

### ISSUE THREAD

**Issue by zeud** [angelsix/fasetto-word#16]
I found this nice and big project. I download the source code  and when I build on first time, I have some error. i search for many times but solution for me.
IDE : Visual studio 2017 
Please help me.
Thank very very much

![error](https://user-images.githubusercontent.com/20393428/34471314-470bcf1e-ef46-11e7-87c4-a80579019db0.JPG)

**Comment by angelsix** [comment]
Looks like your VS has downgraded it to .Net Framework 4.7. Right click the project select properties. Is it targeting 4.7.2?

**Comment by zeud** [comment]
no it targeting 4.7

**Comment by angelsix** [comment]
Download it from here and it will show and then work. You need 4.7.2
https://www.microsoft.com/net/download/visual-studio-sdks

**Comment by zeud** [comment]
i found the solution by update visual studio
