### ISSUE TITLE
Spelling Issue in the Font ResourceDictionary

### ISSUE THREAD

**Issue by FetzenRndy** [angelsix/fasetto-word#17]
The values of the Font's ResourceDictionary are misspelled. The faulty keys are [here](https://github.com/angelsix/fasetto-word/blob/develop/Source/Fasetto.Word/Styles/Fonts.xaml#L6)

The current path is:
`pack://appliction;,,,/Fonts/<FONT_NAME>`
but should be
`pack://application;,,,/Fonts/<FONT_NAME>`

So "application" is just misspelled.

**Comment by angelsix** [comment]
You know I remember finding that months ago and forgetting to fix it. The odd thing is it works with the typo that's what was confusing me also. 

Can you send a pull request with the fix? If not I'll push a fix later

**Comment by FetzenRndy** [comment]
Pull request sent

**Comment by angelsix** [comment]
Thanks. Merged
