### ISSUE TITLE
MainWindow.xaml error with IsBusyProperty

### ISSUE THREAD

**Issue by Rainson12** [angelsix/fasetto-word#22]
I seem to get the following error and i have no idea on how to resolve it. Any help would be appreciated.

Severity	Code	Description	Project	File	Line	Suppression State
Error		GenericArguments[0], 'HRM.AttachedProperties.IsBusyProperty', on 'HRM.AttachedProperties.BaseAttachedProperty`2[Parent,Property]' violates the constraint of type parameter 'Parent'.	Indivumed.HRM	C:\Users\Rainson\Documents\Visual Studio 2017\Projects\HRM\HRM\MainWindow.xaml	115

**Comment by Rainson12** [comment]
I am at your yt guide #12. Which update contains the changes?

**Comment by angelsix** [comment]
13 video on WPF on April 23rd 2017 https://github.com/angelsix/fasetto-word/commit/10a274f11ed2a10262afc7b89332a0e4ec1553d1

https://youtu.be/0IE4osmIV0g
