### ISSUE TITLE
LoginViewModel binding for Email not working 

### ISSUE THREAD

**Issue by thoraj** [angelsix/fasetto-word#26]
First of all; thanks a lot for generously making this application and the videos available. This is invaluable for a WPF beginner like myself.

The issue we are exeriencing in the LogInView is that typing an email and pressing ENTER does not work (Email property is null). Clicking the button works as expected (Email property is populated). 

Should not the Binding for the Email property work independently of how the command is invoked (ENTER or button-click)?

--
Thor A. Johansen

**Comment by angelsix** [comment]
Good catch. We need to update the view model when the property changes, not on lost focus. `UpdateSourceTrigger=PropertyChanged`. Fixed here https://github.com/angelsix/fasetto-word/commit/ed9a5fb55422ac65b61dc39cacfd1e006c0f178b

**Comment by thoraj** [comment]
Wow. 

8 minutes to respond and fix :-)

I impressed and thankful. 

Thanx
--
Thor Arne
