### ISSUE TITLE
Use Fasetto.Word.Web.Server in WPF-Project

### ISSUE THREAD

**Issue by Ghislain1** [angelsix/fasetto-word#27]
Hello Guy,
Can you tell me how i can referent your project  "Fasetto.Word.Web.Server" to WPF-Project?

Repro Step:

- Creat a WPF Project
- Add Button named Start Server
- Add Events to launch the Server in background by clicking on Button

I try to use the Nuget package approch but it s not work. Do you have any  approch to solve this?

Thank you in Advanced
Ghislain from Germany!!

**Comment by angelsix** [comment]
When you say reference what are you trying to do? If you mean to actually start a server, just publish the server with `dotnet publish -r win-x64 -c Release --output SomeOutputFolderName` inside the folder where the solution file to the server is. Then you will have a folder called `SomeOutputFolderName` and in there an exe you can run to spin up the server.

So from there you could just do `Process.Start("location\of\server.exe");`
