### ISSUE TITLE
Snapping/docking in certain conditions

### ISSUE THREAD

**Issue by poiyomi** [angelsix/fasetto-word#3]
The window fails to snap/dock to the edges correctly if the start bar is not on the bottom of the monitor or if the monitor is not 16:9 aspect ratio.

**Comment by angelsix** [comment]
Are you using the very latest branch? I have just checked with the start/taskbar docked to the left, right and top and works fine. I've tried multi-monitor setup, multiple DPI resolutions, and on an ultrawide 4k monitor. All docking works fine

**Comment by poiyomi** [comment]
Sorry for the late reply. When the start bar is on top with the latest version of this project it looks like this.

I'm using a 3 monitor setup [2160p][1440p][1080p]

![capture](https://cloud.githubusercontent.com/assets/8877018/26532912/10023bc2-43dc-11e7-9498-c44b734dd7b9.PNG)

**Comment by angelsix** [comment]
Fixed in 7e6735ad36795d7051261c98eae6f363b2c39a7d https://github.com/angelsix/fasetto-word/commit/7e6735ad36795d7051261c98eae6f363b2c39a7d
