### ISSUE TITLE
vertical dock, corner dock and maximize bug

### ISSUE THREAD

**Issue by poiyomi** [angelsix/fasetto-word#4]
When resizing vertically to the extent of the monitor the window docks with a gap
![image](https://cloud.githubusercontent.com/assets/8877018/26563154/d2e985b8-449b-11e7-9450-f52b2e9e6ef6.png)

When dragging window to a corner of the monitor it docks with a gap
![image](https://cloud.githubusercontent.com/assets/8877018/26563169/0205fe58-449c-11e7-849a-0aa3072d26ce.png)

When window is anywhere on left monitor and is maximized this is the result (sorry for image size)
![untitled-1](https://cloud.githubusercontent.com/assets/8877018/26563203/7aeabe8a-449c-11e7-8d76-0ea3d14a9f03.jpg)

When window is anywhere on right monitor and maximized it disappears entirely I assume because it's docking to the top right corner of the total desktop rectangle.
[image of empty desktop with same layout as previous image]

I can reorganize my monitors for a variety of results.
![untitled-1](https://cloud.githubusercontent.com/assets/8877018/26563247/2a154b00-449d-11e7-98a8-b844d03f9a68.jpg)

**Comment by angelsix** [comment]
Fixed 1 and 2 in https://github.com/angelsix/fasetto-word/commit/357be0125e6e2502ac5f496e5ea8e6d7610f0058

Cannot reproduce issue 3 with "left monitor". Can you try and isolate the issue. Does it happen on your system with 1 monitor, 2 monitors or only 3?

Also, if it happens with just 2 monitors, does swapping the position left/right change the issue?

Also does display resolution change the issue?

**Comment by poiyomi** [comment]
I'll test right after work and see if I can isolate exactly what's happening.

**Comment by poiyomi** [comment]
3 monitors different resolutions: maximize on anything but main monitor causes incorrect positioning
3 monitors same resolution: same thing
2 monitors same resolution: same thing

It seems that maximizing on anything that isn't the main monitor does not function correctly.

https://youtu.be/vYBIU5_-3Ig here's a video of 2 1080p monitors

**Comment by angelsix** [comment]
Regression bug. Fixed here hopefully https://github.com/angelsix/fasetto-word/commit/2f5c42afe5b9b77768fe2f77d7d21a293499e718

Please check and let me know

**Comment by poiyomi** [comment]
Checking Now

**Comment by poiyomi** [comment]
It's all good now. Keep up the hard work!
