### ISSUE TITLE
Design Time Exception

### ISSUE THREAD

**Issue by BEDIRHANSAMSA** [angelsix/fasetto-word#47]
Hello,

I am getting this error:    

at System.Windows.Controls.Page.System.Windows.IWindowService.get_Width()
   at System.Windows.Controls.Page.get_WindowWidth()
   at UI.Animation.PageAnimations.SlideAndFadeInFromRight(Page page, Single seconds) in UI\Animation\PageAnimations.cs:line28
   at UI.Pages.BasePage`1.AnimateIn() in \UI\Pages\BasePage.cs:line 115
   at UI.Pages.BasePage`1.BasePage_Loaded(Object sender, RoutedEventArgs e) in \UI\Pages\BasePage.cs:line 97
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   
   
![image](https://user-images.githubusercontent.com/44173331/121211263-03822b00-c885-11eb-8f5b-d3ecb3b3e5bb.png)

Because of this method:
![image](https://user-images.githubusercontent.com/44173331/121211308-0da42980-c885-11eb-9aaf-2518fb18d765.png)
If I change like this page.WindowWidth to 700:
![image](https://user-images.githubusercontent.com/44173331/121211551-3f1cf500-c885-11eb-9459-14b1653c2128.png)

It's working, how can I fix this?

![image](https://user-images.githubusercontent.com/44173331/121211403-214f9000-c885-11eb-94d3-20638237c3a9.png)

**Comment by joshman1019** [comment]
You may want to disable project code when working with this page. The page is attempting to gather the window width while in design time mode and fails. On the XAML designer you can enable and disable project code easily. 

![image](https://user-images.githubusercontent.com/36560776/121388646-a4bac100-c919-11eb-94dd-75b79b82f86c.png)

As an aside: I would recommend using event triggers and storyboards instead of animating in the code-behind. It will make your life easier when using the designer. His method for animating was good, but I found it overly complicated and hard to debug. Cases like this popped up all of the time. You can easily make a custom animation control that can be used across other projects.

**Comment by ahmedtalaat327** [comment]
> Hello,
> 
> I am getting this error:
> 
> at System.Windows.Controls.Page.System.Windows.IWindowService.get_Width() at System.Windows.Controls.Page.get_WindowWidth() at UI.Animation.PageAnimations.SlideAndFadeInFromRight(Page page, Single seconds) in UI\Animation\PageAnimations.cs:line28 at UI.Pages.BasePage`1.AnimateIn() in \UI\Pages\BasePage.cs:line 115 at UI.Pages.BasePage`1.BasePage_Loaded(Object sender, RoutedEventArgs e) in \UI\Pages\BasePage.cs:line 97 at System.Threading.Tasks.Task.<>c.b__139_0(Object state) at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs) at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> 
> ![image](https://user-images.githubusercontent.com/44173331/121211263-03822b00-c885-11eb-8f5b-d3ecb3b3e5bb.png)
> 
> Because of this method: ![image](https://user-images.githubusercontent.com/44173331/121211308-0da42980-c885-11eb-9aaf-2518fb18d765.png) If I change like this page.WindowWidth to 700: ![image](https://user-images.githubusercontent.com/44173331/121211551-3f1cf500-c885-11eb-9459-14b1653c2128.png)
> 
> It's working, how can I fix this?
> 
> ![image](https://user-images.githubusercontent.com/44173331/121211403-214f9000-c885-11eb-94d3-20638237c3a9.png)

The only solution I've found is by adding `d:Content="{Binding}"` inside the frame itself not the page.
