### ISSUE TITLE
Question - Pass data between Viewmodels

### ISSUE THREAD

**Issue by BEDIRHANSAMSA** [angelsix/fasetto-word#48]
Hi,

I have a view model field and I want to send another view model.  I cant use object initialize because the constructor executions first and this field is null. I need this field in the constructor. I tryed constructor parameter but that didnt work i get a error;

![image](https://user-images.githubusercontent.com/44173331/131515559-85dd01f2-2e91-41ec-9ee8-897f7a6b9cee.png)

Error:
`'ProductDetailViewModel' must be a non-abstract type with a public parameterless constructor in order to use it as parameter 'TVm' in the generic type or method 'BasePage<TVm>'`

P.S: sorry for my English :|
Thanks

**Comment by joshman1019** [comment]
I think a bit more information may be needed in order to answer your question. There is not enough code posted to determine the control flow of your app up to this point. Typically, if passing a base page or something similar into a ViewModel I would use an interface. But that's just what I can gather from what is posted. I will be glad to help if you can give a bit more context.

**Comment by BEDIRHANSAMSA** [comment]
Hi, thanks for your answer.

I have a Product List page and I want to which in the list double-clicked product id send product details page but I can't send it product id to product detail view model. How can I send Product Id another view model?

I tried field-initialization but not work because if the class has a constructor, first initializing constructor and after sets fields. Example: 
![image](https://user-images.githubusercontent.com/44173331/131892315-8c0b9ffb-a597-48f2-a8fd-f04074fa99cc.png)
![image](https://user-images.githubusercontent.com/44173331/131892320-d7c2e763-aa60-4d45-9e1f-3dcd30f8849f.png)

I tried ProductDetail constructor parameter but I got an error;
`'ProductDetailViewModel' must be a non-abstract type with a public parameterless constructor in order to use it as parameter 'TVm' in the generic type or method 'BasePage<TVm>'
`

Sorry for my bad English. 

I'm using BasePage and BaseViewModel.
https://github.com/angelsix/fasetto-word/blob/25d24288cbd80e6534b0e389b6c2c2b608eb565d/Source/Fasetto.Word/Pages/BasePage.cs#L1-L224
https://github.com/angelsix/fasetto-word/blob/25d24288cbd80e6534b0e389b6c2c2b608eb565d/Source/Fasetto.Word/ViewModel/Base/BaseViewModel.cs#L1-L111

Product List:
![image](https://user-images.githubusercontent.com/44173331/131892060-865204a6-a535-487b-8bd0-e2a9594d9459.png)

**Comment by joshman1019** [comment]
I have personally used some sort of state storage for issues like this. I use the MVVM pattern for all of my WPF applications and this is always an issue when loading a new page that is dependent on the data obtained from another. 

So your product list page's viewmodel would store the ID in the state manager, and when loaded, the product detail page would retrieve the ID from the state manager. That decouples the two pages from one another. 

You could store this state in a database, in a static StateManager class, or some other solution that you feel is best for your application. I'm not sure what methods other MVVM developers use but this has always been the best for my use case. Other methods that I've seen are overly complicated, add way too many steps, and are difficult to maintain and debug. 

Without seeing the entire code base I cannot make a solid recommendation, but hopefully this will get you started.

**Comment by joshman1019** [comment]
Honestly, I tried to use a similar pattern to create a WPF application in the past and had some issues like this. 

I never load pages by passing view models. I always allow a page to load a new view model in their constructor and retrieve the data from some sort of state storage that will work for your application.

Again, it is hard to determine without seeing the entire code base, but you might try something similar to avoid these issues.

**Comment by BEDIRHANSAMSA** [comment]
Hi, thanks for your answer and the interest you have shown. I think I found a solution. I changed my Base Page<Product Detail View Model> to BasePage in Xaml File and constructor like this;

```csharp
#region Constructor

/// <summary>
/// Default constructor
/// </summary>
public ProductDetail(Product product)
{
    InitializeComponent();
    ViewModelObject = new ProductDetailViewModel(product);
}

#endregion
```

In This way I can define fields viewmodel constructor.
```csharp
#region Constructor

/// <summary>
/// Default constructor
/// </summary>
public ProductDetailViewModel(Product product)
{
    // Set product
    Product = product;
}

#endregion
```
