### ISSUE TITLE
Window can't be resized while docked

### ISSUE THREAD

**Issue by poiyomi** [angelsix/fasetto-word#5]
Normal windows can be resized when docked this one can't.
![gif](https://cloud.githubusercontent.com/assets/8877018/26762177/797b21e8-490b-11e7-9f07-b84530397e99.gif)

**Comment by angelsix** [comment]
Fixed in https://github.com/angelsix/fasetto-word/commit/a9ff595a69d98ea35f71190bfb422f643e7e0b27

Please confirm

**Comment by poiyomi** [comment]
Confirmed to be working.
