### ISSUE TITLE
Full screen bug

### ISSUE THREAD

**Issue by BasilisXs** [angelsix/fasetto-word#7]
i noticed that when i go full screen the borders on the gui are not right.
i took a screenshot with windows Sniping Tool on window snip mode and this is what i got:
(this running to secondary monitor with bigger resolution )
![bug](https://user-images.githubusercontent.com/29635089/28875887-ea592546-779f-11e7-9918-05c3fd115938.PNG)

**Comment by angelsix** [comment]
Is this on the latest code? I fixed all those types of issues in bug fixes before.

If so, please can you provide the following:

1. What is the resolution, position (left, right, top, bottom etc...) on the multi-monitor layout, and scaling factor (100%, 150% etc..) of the main monitor

2. What is the resolution, position (left, right, top, bottom etc...) on the multi-monitor layout, and scaling factor (100%, 150% etc..) of the second monitor


And try the following:

1. Change your monitors to both be the same Scaling of 100%. Is the problem still there?
2. Change them both to be 200%. Is the problem still there?

**Comment by BasilisXs** [comment]
Yes this is on latest version.
you really lost me on those questions so ill just tell you some more info :)

there are 2 monitors. the laptop and the monitor one.
the small laptop one works on 1600x900 resolution with no gpu scale from ati control panel and 100% scale on windows  scaling.
Same with the monitor but with 1920x1080 resolution.

if i force windows to use 200% scale on both monitors the things are worst!

please let me know if there is any further information i can provide you.
if the whole thing seems really messy and you care about solving it i would be happy to teamviewer me so you can see and work on the problem at the same time.
in any case thank you for teaching us! 

![bug2](https://user-images.githubusercontent.com/29635089/28884654-6c54733c-77bb-11e7-8cc5-74560f6c56de.PNG)


![b1](https://user-images.githubusercontent.com/29635089/28884997-cc76f43c-77bc-11e7-8bf2-a488c96bc5e6.png)
![b2](https://user-images.githubusercontent.com/29635089/28884998-cc8877e8-77bc-11e7-8420-0f20a91f3855.png)

**Comment by angelsix** [comment]
Ah this is the known bug https://github.com/angelsix/fasetto-word/blob/develop/Source/Fasetto.Word/Window/WindowResizer.cs#L342

Your non-primary monitor has a larger width. 

I've applied a fix that has a simple limitation right now... your window cannot be larger than the current monitors size. In future I plan to do a better fix to remove that limitation, but it is better than the current bug.

https://github.com/angelsix/fasetto-word/commit/4e681585ff84df59a969a2573239747745ceb688

Confirm fix and I will close the bug

**Comment by BasilisXs** [comment]
works perfectly now on the bigger screen and seems there is no need for a better fix.
looks like pretty normal to me as it is on this version.
