### ISSUE TITLE
Maximized window cant grab from very top side

### ISSUE THREAD

**Issue by BasilisXs** [angelsix/fasetto-word#8]
One next thing that should be fixed in the future is that : 
while you are on full screen big or small monitor doesn't matter, you cant grab the window from the top edges so you can bring it back to (not maximized) state and move it around.
sorry in advance if you already know the issue.

**Comment by angelsix** [comment]
Fixed here https://github.com/angelsix/fasetto-word/commit/3dd1f804a50c1989ac0dc5f68d22cff225a1e081

Please test and confirm

**Comment by BasilisXs** [comment]
you know what are you doing...
Works Fine!
